alias hnix='$EDITOR /etc/nixos/configuration.nix' ## hx
alias l='ls -lAFgG --color=auto' ## etc
alias n='nvim' ## etc
alias sudo='doas' ## doas
alias ga='git add' ## git
alias gau='git add -u' ## git
alias gc='git commit' ## git
alias gC='git commit --amend --no-edit' ## git
alias gd='git diff' ## git
alias gch='git checkout' ## git
alias gchb='git checkout -b' ## git
alias gll="git log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit" ## git
alias gl="gll -n5" ## git
alias halias='$EDITOR ~/.config/.aliases.sh' ## hx
alias gpu='git push' ## git
alias grh='git reset --hard' ## git
alias gs='git status' ## git
alias gpl='git pull' ## git
alias gdh='git diff HEAD~' ## git
alias gds='git diff --staged' ## git
alias python='python3' ## python3
alias hsway='$EDITOR ~/.config/sway/config' ## hx
alias hzsh='$EDITOR ~/.config/zsh/.zshrc' ## hx
alias hkitty='$EDITOR ~/.config/kitty/kitty.conf && kill -SIGUSR1 $KITTY_PID'
alias c="npx @openai/codex@latest resume"
alias gst="git stash"
alias gb="git branch"
alias gres="git restore"
alias e='emacsclient'
