[language-server]
jdtls = { command = "jdt-language-server" }
language-server = { command = "jdt-language-server", args = [
  "-data", "/home/c/.cache/jdtls/workspace"
  ]}

[[language]]
name = "java"
scope = "source.java"
injection-regex = "java"
file-types = ["java"]
roots = ["pom.xml", "build.gradle", ]
indent = { tab-width = 4, unit = "    " }
language-servers = [ "jdtls" ]
