#!/bin/sh

PATH=/sbin:/usr/sbin:/bin:/usr/bin

modprobe i915

# Mount missing psudo-fs
mount -o nosuid,noexec,nodev -t efivarfs efivarfs /sys/firmware/efi/efivars
mount -n -t securityfs securityfs /sys/kernel/security
mount -t cgroup2 -o nsdelegate cgroup2 /sys/fs/cgroup

# Load static modules
for mod in $(kmod static-nodes 2>/dev/null | awk '/Module/ {print $2}'); do
	modprobe -bq $mod 2>/dev/null &
done

# Start udev
/lib/systemd/systemd-udevd --daemon &
udevadm trigger --action=add --type=devices &
udevadm trigger --action=add --type=subsystems &
sleep 2

# Hardware clock
hwclock --systz

btrfs device scan

chown c /dev/dri/renderD128

swapon -a

ip link set up dev lo

echo "XPS" > /proc/sys/kernel/hostname
ln -sf /usr/share/zoneinfo/US/Eastern /etc/localtime

mkdir -p /run/runit
touch /etc/runit/stopit
chmod 0 /etc/runit/stopit
