#!/bin/sh

PATH=/sbin:/usr/sbin:/bin:/usr/bin

# Enable udev and devices
udevd --daemon
udevadm trigger --action=add --type=subsystems
udevadm trigger --action=add --type=devices
udevadm settle

# Setup up console fonts
_index=0
while [ ${_index} -le 10 ]; do
	setfont latarcyrheb-sun32 -C "/dev/tty{_index}"
	_index=$((_index + 1))
done

# Enable swap
swapon -a

# Set up loopback interface
ip link set up dev lo

# Load hostname
cat /etc/hostname > /proc/sys/kernel/hostname

# Set timezone
ln -sf /usr/share/zoneinfo/US/Eastern /etc/localtime

dmesg > /var/log/dmesg.log
chmod 0644 /var/log/dmesg.log

touch /etc/runit/stopit
chmod 0 /etc/runit/stopit
