#!/bin/sh
exec >/dev/console 2>&1
PATH=/sbin:/usr/sbin:/bin:/usr/bin

sv force-shutdown /etc/service/getty-*
sv force-shutdown /etc/service/*
udevadm control --exit
pkill -s0,1 -TERM
pkill -s0,1 -KILL
swapoff -a
umount -r -a -t nosysfs,noproc,nodevtmpfs,notmpfs
mount -o remount,ro /
